yallop/ocaml-ctypes

- Makefile.tests
- src/cstubs/cstubs.ml
- src/cstubs/cstubs.mli
- src/cstubs/cstubs_c_language.ml
- src/cstubs/cstubs_emit_c.ml
- src/cstubs/cstubs_generate_c.ml
- src/cstubs/cstubs_generate_c.mli
- src/cstubs/cstubs_generate_ml.ml
- src/cstubs/cstubs_generate_ml.mli
- tests/test-callback_lifetime/test_callback_lifetime.ml
- tests/test-foreign_values/stub-generator/driver.ml
- tests/test-foreign_values/stubs/functions.ml
- tests/test-foreign_values/test_foreign_values.ml
- tests/tests-common/tests_common.ml
Add a `foreign_value` function to Cstubs for accessing global variables:
```ocaml
val foreign_value : string -> 'a Ctypes.typ -> 'a Ctypes.ptr fn
```
The behaviour is analogous to [Foreign.foreign_value][foreign-foreign-value]: given a type representation `t` and the name of a global value `n`, `foreign_value t n` returns the address of the global.  For example, POSIX specifies a global variable holding the process environment:
```C
char **environ;
```
To bind to `environ` we might write
```ocaml
foreign_value "environ" (ptr string_opt)
```
which returns a value of type `string option ptr ptr` (corresponding to `char ***`) which can be used to read and write to `environ`.
Closes #136.
[foreign-foreign-value]: http://ocamllabs.github.io/ocaml-ctypes/Foreign.html#VALforeign_value
> Extend Cstubs with foreign_value support

- Makefile.tests
- src/configure/make_primitive_details_stubs.c
- src/cstubs/cstubs.mli
- src/cstubs/cstubs_c_language.ml
- src/cstubs/cstubs_structs.ml
- src/cstubs/cstubs_structs.mli
- src/ctypes/type_info_stubs.c
- tests/clib/test_functions.h
- tests/test-constants/stub-generator/driver.ml
- tests/test-constants/stubs/types.ml
- tests/test-constants/test_constants.ml
This pull request adds support for retrieving constants (`#define`s, enums, etc.) from C.
There's a new function
```ocaml
val constant : string -> 'a typ -> 'a const
```
which retrieves the value of a named compile-time constant of a given type.  It can be used to retrieve enum constants, #defined values and other integer constant expressions.
The type `typ` must be either an integer type such as `bool`, `char`, `int`, `uint8`, etc., or a view (or perhaps multiple views) where the underlying type is an integer type.
When the value of the constant cannot be represented in the type there will typically be a diagnostic from either the C compiler or the OCaml compiler.  For example, gcc will say
```
warning: overflow in implicit constant conversion
```
Closes #235.
> Support for retrieving constants from C.

- Makefile.tests
- src/cstubs/cstubs.mli
- src/cstubs/cstubs_internals.ml
- src/cstubs/cstubs_internals.mli
- src/cstubs/cstubs_structs.ml
- src/cstubs/cstubs_structs.mli
- src/ctypes/ctypes_primitives.h
- src/ctypes/posixTypes.ml
- src/ctypes/posix_types_stubs.c
- src/ctypes/static.ml
- src/ctypes/static.mli
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-enums/struct-stub-generator/driver.ml
- tests/test-enums/struct-stubs/types.ml
- tests/test-enums/stub-generator/driver.ml
- tests/test-enums/stubs/functions.ml
- tests/test-enums/test_enums.ml
This pull request adds support for using enum types.
There's a new function
```ocaml
val enum : string -> ?unexpected:(int64 -> 'a) -> ('a * int64 const) list -> 'a typ
```
which builds a type representation for a named enum.  The size and alignment are retrieved from C so that the resulting type can be used everywhere an integer type can be used: as an array element or struct member, as an argument or return value, etc.
The last argument is an association list of OCaml values and values retrieved by the [constant] function.  For example, to expose the enum
```C
enum letters { A, B, C = 10, D }; 
```
you might first retrieve the values of the enumeration constants:
```ocaml
let a = constant "A" int64_t
and b = constant "B" int64_t
and c = constant "C" int64_t
and d = constant "D" int64_t …
```
> Add support for enum types

- appveyor.yml
- appveyor/build.sh
Just a test pull request in order to investigate: https://github.com/ocamllabs/ocaml-ctypes/issues/256
Changes:
- use pre-installed cygwin and libffi
- don't hardcode the mirror (I assume that was the only problem. Haxe uses a similar setup and they don't seem to have any problems )
> appveyor: use pre-installed cygwin and libffi

- src/cstubs/cstubs_generate_ml.ml
> Use an external name for managed_buffer in generated code.

- Makefile
- src/discover/commands.ml
- src/discover/commands.mli
- src/discover/determine_as_needed_flags.sh
- src/discover/discover.ml
Various improvements
* Communicate via argument passing rather than globals
* A module to run commands and capture stdout/stderr/status
* Simplify input/output structure: write output to stdout and diagnostics to stderr
* Remove some hand-rolled functions that duplicate standard library functionality
* Simplified control flow (e.g. no passing of "fallback" functions)
* Split out the `-Wl,-no-as-needed` linker flag detection into a separate script
* Don't generate unnecessary/unused header files and modules 
This should leave behaviour more or less unchanged, but should make it easier to fix various configuration-related issues (e.g. #20)
Closes #172.
> Refactor discover.ml

- .gitignore
- Makefile
- appveyor/build.sh
- src/discover/discover.ml
Split up the base, foreign and stubs sub-projects so that the latter two are optional.
1. There are new top-level build targets, so that you can run
```
make ctypes-base
make ctypes-foreign
make ctypes-stubs
```
and just build the components you need.  This supersedes #91.
2. `libffi` is no longer required if you're not using the `foreign` subpackage.  Closes #195.
3. If you try to build the `foreign` subpackage when `libffi` is not available the build process exits with a helpful error message:
```
The following required C libraries are missing: libffi.
Please install them and retry. If they are installed in a non-standard location
or need special flags, set the environment variables <LIB>_CFLAGS and <LIB>_LIBS
accordingly and retry.
For example, if libffi is installed in /opt/local, you …
```
> Add top-level build targets for individual components

- src/cstubs/cstubs_inverted.ml
> Use the new #include path for ctypes_cstubs_internals.h.

- src/discover/discover.ml
Hello,
There is a typo in the code that detects `libffi`. It causes the detection to fail when providing `LIBFFI_{CFLAGS,LIBS}`. Please see the attached fix.
Thanks!
> Fix a typo in libffi detection code

- src/cstubs/cstubs_analysis.ml
- src/cstubs/cstubs_generate_c.ml
- src/cstubs/cstubs_generate_ml.ml
- src/cstubs/cstubs_internals.ml
- src/cstubs/cstubs_internals.mli
- src/ctypes-foreign-base/ctypes_ffi.ml
- src/ctypes-foreign-base/ctypes_ffi.mli
- src/ctypes-foreign-base/ctypes_ffi_stubs.ml
- src/ctypes-foreign-base/ctypes_foreign_basis.ml
- src/ctypes-foreign-base/ffi_call_stubs.c
- src/ctypes/ctypes.mli
- src/ctypes/ctypes_coerce.ml
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_ptr.ml
- src/ctypes/ctypes_static.ml
- src/ctypes/ctypes_static.mli
- src/ctypes/ctypes_std_views.ml
- src/ctypes/ctypes_type_printing.ml
- src/ctypes/ctypes_types.mli
- src/ctypes/ctypes_value_printing.ml
- tests/test-higher_order/stubs/functions.ml
- tests/test-higher_order/test_higher_order.ml
- tests/test-raw/test_raw.ml
In standard C, object pointers (such as `void *`) and function pointers (such as `void(*)(void)`) are not compatible.  This pull request reflects that incompatibility by distinguishing them in ctypes' core language (i.e. Ctypes_static.typ).  This is mostly an internal change, but there are a couple of externally-visible additions:
* A new type `static_funptr` and and accompanying type representation constructor of the same name.  This is less flexible than `Foreign.funptr`, but doesn't rely on `libffi`.  You can use `static_funptr` to store function pointers returned from C, and to pass those function pointers back to C:
```ocaml
let qsort = foreign "qsort"
(ptr void @-> size_t @-> size_t @->
static_funptr (ptr void @-> ptr void @-> returning int) @->
returning void)
```
However, …
> Support function pointers in the core type representation

- src/ctypes/ctypes_std_view_stubs.ml
- src/ctypes/ctypes_std_views.ml
- src/ctypes/ctypes_types.mli
- src/ctypes/unsigned_stubs.c
> Add support for ptrdiff_t as a typedef for a signed integer type.

- src/cstubs/cstubs_structs.ml
- src/ctypes/ctypes_structs_computed.ml
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-structs/stubs/types.ml
- tests/test-structs/test_structs.ml
- tests/test-unions/stubs/types.ml
- tests/test-unions/test_unions.ml
It's common style in C code to omit struct tags, relying on typedefs to identify types instead:
```C
typedef struct {
int x;
float y;
} t;
```
Here is the corresponding ctypes code:
```ocaml
let struct_t = structure ""
let t = typedef struct_t "t"
let x = field t "x" int
let y = field t "y" float
let () = seal t
```
Unfortunately, this code doesn't currently work, since ctypes relies on struct tags in generated code and rejects typedefs and other views when computing layout.  This pull request addresses that problem, so that both struct tags and typedef names can be used to retrieve layout information (fcbb5a7), and so that the code for computing struct layout treats views transparently (d286f5d).
> Support adding fields to structs identified by typedefs

- .depend
- Makefile.tests
- src/ctypes/ctypes.mli
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_roots.c
- src/ctypes/ctypes_roots_stubs.ml
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-roots/test_roots.ml
When exposing OCaml libraries to C (e.g. via [Cstubs_inverted](https://github.com/ocamllabs/ocaml-ctypes/blob/master/src/cstubs/cstubs_inverted.mli)) it's useful to give C code references to OCaml values and control over their lifetimes.  The `Ctypes.Root` module provides functions for creating, reading, updating and releasing OCaml roots that can be passed to C as `void*` values:
```ocaml
module Root :
sig
val create : 'a -> unit ptr
(** [create v] allocates storage for the address of the OCaml value [v],
registers the storage as a root, and returns its address. *)
val get : unit ptr -> 'a
(** [get p] retrieves the OCaml value whose address is stored at [p]. *)
val set : unit ptr -> 'a -> unit
(** [set p v] updates the OCaml value stored as a root at [p]. *)
val release : unit ptr -> …
```
> Support for registering OCaml values as roots

- src/ctypes/managed_buffer_stubs.c
Hello. I'm doing a large-scale study of C stub sources on OPAM.
Your library makes use of the undocumented `caml_stat_*` functions, which currently are thin wrappers around `malloc`, `realloc`, and `free` from the C standard library. In future, the implementation of these functions [may change](https://github.com/ocaml/ocaml/pull/71), making them incompatible with `malloc` and breaking the code that abused the old undocumented semantics.
Regardless of whether the change of semantics will happen or not, being consistent about such matters should be considered good style.
> Fix: inconsistent use of caml_stat_* functions

- src/ctypes/ctypes_roots.c
Each invocation of `ctypes_caml_roots_create` seems to be leaking a "pointerful" of memory. Caught this as part of a large-scale audit of C stubs related to [this PR](https://github.com/ocaml/ocaml/pull/71).
> Fix: a memory leak in ctypes_caml_roots_release

- src/ctypes-foreign-base/ffi_type_stubs.c
- src/ctypes/ctypes.mli
- src/ctypes/ctypes_managed_buffer_stubs.h
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_memory_stubs.ml
- src/ctypes/managed_buffer_stubs.c
- src/ctypes/raw_pointer_stubs.c
This uses `calloc` under the hood to give the OS a chance to optimize if it tags pages as zeroed.
Please review and let me know how you'd like this expressed/integrated and if you see any issues.
Thanks!
> Allocate zeros

- src/ctypes/ctypes.mli
- src/ctypes/ctypes_coerce.ml
- tests/test-coercions/test_coercions.ml
This PR partially addresses #338 by adding additional information to the `Uncoercible` exception, which was previously declared as follows:
```ocaml
exception Uncoercible
```
and is now declared as follows:
```ocaml
exception Uncoercible of uncoercible_info
```
where `uncoercible_info` is an abstract type.  Additionally, the PR registers a printer for `Uncoercible` that displays the source and target types of the failed coercion.  Here's an example program
```
$ cat uc.ml
let _ = Ctypes.(coerce int string) 3
$ ocamlfind c -o uc  -package ctypes -linkpkg uc.ml
```
which previously behaved like this:
```
$ ./uc
Fatal error: exception Ctypes_coerce.Uncoercible
```
and now behaves like this:
```
$ ./uc
Fatal error: exception Coercion failure: int is not coercible to char*
```
> Expose more information in the Uncoercible exception.

- src/ctypes/ctypes_std_views.ml
- src/ctypes/posixTypes.ml
- src/ctypes/posixTypes.mli
A number of the POSIX types, such as `dev_t` and `ino_t`, are [specified to be integers](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html), not just arithmetic types, which means that we can expose arithmetic operations for them.
In cases such as `pid_t` where the type is known to be signed, this PR exposes a module of type [`Signed.S`](http://ocamllabs.github.io/ocaml-ctypes/Signed.S.html) for the type.  In cases such as `mode_t` where the signedness is not specified, the exposed module has type [`Unsigned.S`](http://ocamllabs.github.io/ocaml-ctypes/Unsigned.S.html), which is a subtype of `Signed.S`.
Fixes #87.
>  Expose arithmetic operations for POSIX arithmetic types

- src/ctypes/posixTypes.ml
- src/ctypes/posixTypes.mli
I'm not actually sure this is correct, but I need a time_t exposed in such a way that I can convert an integer to it, is there a more correct way to do this?
> Expose time_t as an unsigned value

- README.md
Link to @simonjbeaumont's very useful introduction to `Cstubs`.  Closes #331.
> Add a link to "Type-safe C bindings using ocaml-ctypes and stub generation"

- src/ctypes/ctypes.ml
- src/ctypes/ctypes.mli
This pull request removes `*:*` and `+:+`, which have been deprecated since 510b7a8f6747a8422bccc15fe4050d034ea134c9 (August 2013), and since the 0.2.0 release.
Initially, structs were defined as follows in ctypes:
```ocaml
let s : s structure typ = structure "s"
let x = s *:* int 
let y = s *:* float 
let () = seal s
```
However, struct fields have names, and those names turn out to be useful when generating C code.  The [`field`](http://ocamllabs.github.io/ocaml-ctypes/Ctypes_types.TYPE.html#VALfield) function, which replaces `*:*` and `+:+`, takes an additional argument that specifies the name:
```ocaml
let s : s structure typ = structure "s"
let x = field s "x" int 
let y = field s "y" float 
let () = seal s
```
In [practice](https://github.com/dsheets/profuse/blob/009ffddce0c6d2353e4b …
> Remove the deprecated '*:*' and '+:+' functions.

- src/ctypes-foreign-base/ctypes_ffi.ml
- src/ctypes/ctypes_bigarray.ml
- src/ctypes/ctypes_memory_stubs.ml
- src/ctypes/ctypes_roots.c
- tests/test-bigarrays/test_bigarrays.ml
- tests/test-callback_lifetime/test_callback_lifetime.ml
- tests/test-finalisers/test_finalisers.ml
- tests/test-structs/test_structs.ml
- tests/test-threads/test_threads.ml
@LaurentMazare reports (#381) a potetntial problem that arises with the more aggressive optimization in OCaml 4.03: the optimizer detects that references to values can be eliminated altogether, so the GC collects the values earlier than intended. 285e227 introduces a fix for that problem: the values are "used" by passing them to a C function, whose implementation the optimizer cannot see.  
1f49699 adds a second fix for an optimizer/GC interaction in the tests.  The tests for closure lifetime previously contained code like this, which allocates a closure and passes it to C:
```ocaml
let mul x y = x * y in
c_function (mul 3)
```
The optimizer apparently transformed the code to eliminate the closure, resulting in something like this:
```ocaml
let mul_3 y = 3 * y
c_function mul_3
```
As a …
> Extra care with optimizer/GC interactions

- Makefile.tests
- src/cstubs/cstubs.ml
- src/cstubs/cstubs.mli
- src/cstubs/cstubs_c_language.ml
- src/cstubs/cstubs_emit_c.ml
- src/cstubs/cstubs_generate_c.ml
- src/cstubs/cstubs_generate_c.mli
- src/cstubs/cstubs_generate_ml.ml
- src/cstubs/cstubs_generate_ml.mli
- src/cstubs/cstubs_inverted.ml
- src/ctypes/ctypes_cstubs_internals.h
- tests/test-foreign-errno/test_errno.ml
- tests/test-returning-errno-lwt/stub-generator/driver.ml
- tests/test-returning-errno-lwt/stubs/functions.ml
- tests/test-returning-errno-lwt/stubs/types.ml
- tests/test-returning-errno-lwt/test_returning_errno.ml
- tests/test-returning-errno/stub-generator/driver.ml
- tests/test-returning-errno/stubs/functions.ml
- tests/test-returning-errno/stubs/types.ml
- tests/test-returning-errno/test_returning_errno.ml
- tests/tests-common/tests_common.ml
This pull request adds support for returning [`errno`][errno] alongside the return value of bound functions in generated stubs.  As with #391, the interface changes are fairly modest: there is an additional argument, `errno` to [`write_c`][write_c] and [`write_ml`][write_ml], specifying the policy to use.
Besides the default, `ignore_errno`, there is one additional option, `return_errno`, which changes the return type of each function binding from `t` to `t * int`.
For example, here is the example bindings description for `puts` and `rmdir` from #391:
```ocaml
module Bindings(F: Cstubs.FOREIGN) =
struct
open F
let puts = foreign "puts" (string @-> returning int)
let rmdir = foreign "rmdir" (string @-> returning int)
end
```
The C and OCaml portions of the bindings may be generated in the …
> Support for returning errno from generated stubs

- src/configure/extract_from_c.ml
- src/configure/gen_libffi_abi.ml
The OS X build is currently [failing](https://travis-ci.org/ocaml/opam-repository/jobs/134712983) when `libffi` is not available, because the configuration program always includes `#include <ffi.h>`.
> Configuration: only include <ffi.h> when extracting libffi symbols.

- src/configure/extract_from_c.ml
Otherwise it is a sheer coincidence, if the command get's the proper arguments, at least on windows. Single quotes `'` are not supported at all by `Sys.command` (cmd.exe). I wonder, why the appveyor test passes...
> Quote arguments for Sys.command properly

- src/ctypes-foreign-base/ffi_call_stubs.c
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-higher_order/stubs/functions.ml
- tests/test-higher_order/test_higher_order.ml
When the return type of a function is an integer type narrower than the system register size, [`libffi` promotes it to `ffi_arg`][libffi-promotion].
On big-endian systems, this causes problems with calls to functions that return small integers (`char`, `short`, etc.), since `libffi` writes the return value to an `ffi_arg`-sized slot, and ctypes attempts to read the value from the same address using a pointer to the return type rather than a pointer to `ffi_arg`.
This pull request adds a compensating offset to the return value address passed to ctypes on big-endian systems for both regular function calls (d00922e) and callbacks (d6c200a), and a new test for callbacks that return small integers (9f3cb97).
[libffi-promotion]: https://github.com/libffi/libffi/blob/c0829e62841100c308cc37ddd6537 …
> Fix for PowerPC: handle libffi's integer return type promotion

- Makefile
- Makefile.rules
- Makefile.tests
- src/ctypes-foreign-base/ffi_type_stubs.c
- tests/test-roots/test_roots.ml
Hello,
Here is a branch that fixes compilation and tests on all Debian _release_ architectures.
> Debian fixes

- src/ctypes-top/ctypes_printers.ml
- src/ctypes-top/ctypes_printers.mli
- src/ctypes-top/install_ctypes_printers.ml
```ocaml
- : Signed.SInt.t = <sint 20>
```
> Add a top-level printer for the new 'sint' type.

- .depend
- Makefile
- src/ctypes-foreign-base/ctypes_ffi.ml
- src/ctypes-foreign-base/ctypes_ffi.mli
- src/ctypes-foreign-base/ctypes_ffi_stubs.ml
- src/ctypes-foreign-base/ctypes_foreign_basis.ml
- src/ctypes-foreign-base/ffi_call_stubs.c
- src/ctypes-foreign-threaded/ctypes_foreign_threaded_stubs.ml
- src/ctypes-foreign-threaded/foreign.ml
- src/ctypes-foreign-threaded/foreign.mli
- src/ctypes-foreign-threaded/foreign_threaded_stubs.c
- src/ctypes-foreign-unthreaded/foreign.mli
- tests/test-raw/test_raw.ml
This pull request adds a new argument, `~thread_registration`, to `funptr`.  Passing `~thread_registration:true` indicates that the C thread that calls into OCaml through the function pointer should be registered with the OCaml runtime (via [`caml_c_thread_register`][caml_c_thread_register]).
C threads so registered are automatically unregistered (via `caml_c_thread_unregister`) when they exit.
This functionality is currently unavailable on Windows, which apparently provides little support for running functions on thread termination.  Perhaps it's possible to implement using [`RegisterWaitForSingleObject`][registerwaitforsingleobject]; patches are, of course, very welcome!  (@fdopen: if you have time to look at this, your help would be greatly appreciated.) 
Here's a quick example of the …
> Registration of C threads from callbacks

- Makefile
- Makefile.rules
> Use -opaque for module interfaces whose cmx files are not installed.

- src/cstubs/cstubs_generate_c.ml
Otherwise, APIs which rely on errno to resolve exit code ambiguity (e.g. `readdir`) are not bindable correctly. See dsheets/ocaml-unix-dirent#17 for an example/work-around in that
particular case.
> Reset errno in lwt jobs before invoking job function

- Makefile.tests
- src/cstubs/cstubs.ml
- src/cstubs/cstubs.mli
- src/cstubs/cstubs_generate_c.ml
- src/cstubs/cstubs_generate_c.mli
- src/cstubs/cstubs_generate_ml.ml
- src/cstubs/cstubs_generate_ml.mli
- tests/test-threads/stub-generator/driver.ml
- tests/test-threads/stubs/functions.ml
- tests/test-threads/test_threads.ml
Fixes #241.
This adds an extra value, [`Cstubs.unlocked`](https://github.com/yallop/ocaml-ctypes/blob/2e1d16ddbced122e3076241003dded1db3aaa959/src/cstubs/cstubs.mli#L129-L131) to the interface:
```ocaml
val unlocked : concurrency_policy
(** Generate code that releases the runtime lock during C calls. *)
```
Passing `~concurrency_policy:Cstubs.unlocked` to the `write_c` and `write_ml` functions results in generated code that releases the [runtime lock](http://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec453) when calling C functions.
> Add support for releasing the runtime lock in generated stubs

- src/ctypes/ctypes_memory.ml
- tests/test-returning-errno-lwt-jobs/test_returning_errno.ml
- tests/test-returning-errno-lwt-preemptive/test_returning_errno.ml
```
File "src/ctypes/ctypes_memory.ml", line 316, characters 7-8:
Warning 56: this match case is unreachable.
Consider replacing it with a refutation case '<pat> -> .'
File "src/ctypes/ctypes_memory.ml", line 316, characters 7-8:
```
```
File "tests/test-returning-errno-lwt-jobs/test_returning_errno.ml", line 23, characters 40-43:
Warning 40: lwt was selected from type Generated_bindings.return.
It is not visible in the current scope, and will not 
be selected if the type becomes unknown.
```
> Address a couple of warnings

- Makefile.rules
Hello,
When compiling on OpenBSD I encountered this error
```
ocamlfind ocamlmklib -o _build/ctypes-foreign-base_stubs _build/src/ctypes-foreign-base/dl_stubs.o _build/src/ctypes-foreign-base/ffi_call_stubs.o _build/src/ctypes-foreign-base/ffi_type_stubs.o -L/usr/local/lib -pthread -lffi
ocamlfind: unknown option '-pthread'.
```
That seems related to a line in Makefile.rules.
I fixed that a few weeks ago but can't remember much about the fix itself, I'm not sure I understand what's going on.
I tested it and it looks like it works on Linux and OpenBSD at least.
Do you have any idea on what might be the issue ?
patch attached to fix the problem.
> Fix Makefile.rules on OpenBSD

- src/ctypes-foreign-base/ctypes_ffi.ml
- src/ctypes-foreign-base/ctypes_ffi_stubs.ml
- src/ctypes-foreign-base/ffi_call_stubs.c
- tests/test-cstdlib/test_cstdlib.ml
- tests/test-oo_style/test_oo_style.ml
Tie `libffi` closure lifetime to OCaml closure lifetime.
> Fix a memory leak with trampoline creation

- src/ctypes/ctypes_primitives.h
Previously, when compiling a C file with:
- GCC
- the option -pedantic
- the include line #include "ctypes_cstubs_internals.h"
We had the following warning:
ctypes_primitives.h:47:19: warning: comma at end of enumerator list [-Wpedantic]
Ctypes_Complex64,
This commit remove this warning.
> Remove a GCC warning when compiling with -pedantic

- Makefile.rules
Reverts ocamllabs/ocaml-ctypes#428.
Fixes #442.
> Revert "Fix Makefile.rules on OpenBSD"

- Makefile
- Makefile.rules
- src/ctypes-foreign-base/ctypes_foreign_basis.ml
- src/ctypes-foreign-base/dl.ml.unix
- src/ctypes-foreign-base/dl.ml.win
- src/ctypes-foreign-base/dl.mli
- tests/test-raw/test_raw.ml
Also change the `Dl` interface to use only published types.
See the discussion under #444 [here](https://github.com/ocamllabs/ocaml-ctypes/pull/444#issuecomment-246335325).
> Only install cmti files for modules intended for end users

- src/ctypes/ctypes.mli
- src/ctypes/ctypes_memory.ml
- tests/test-arrays/test_array.ml
> Add some extra CArray functions

- src/ctypes-foreign-threaded/foreign_threaded_stubs.c
Follow up to #420, fix for #421.
Explanation is inside the source as comment.
> Windows support for registration of C threads from callbacks

- tests/clib/test_functions.c
Calling sem_init with `-1` is wrong. The parameter is of type `unsigend int`.
Usually `(unsigned int)-1 > SEM_VALUE_MAX`, so sem_init will fail with `EINVAL`.
`sem_init(&sem,0,0)` was probably intended.
> Fix semaphore usage inside test suite

- src/ctypes/unsigned_stubs.c
Similar to https://github.com/ocamllabs/ocaml-ctypes/pull/433
> Netbsd: standard integer types are also defined as macros

- Makefile.rules
the output of `pkg-config --libs libffi` can contain flags that are not understood by ocamlmklib (like `-pthread`).
The previous solution ( https://github.com/ocamllabs/ocaml-ctypes/pull/428 ) passed the wrong flag to ocamlmklib (`-cclib` instead of `-ldopt`), which caused https://github.com/ocamllabs/ocaml-ctypes/issues/442 . (`-cclib` options are ignored, because ocamlmklib neither calls ocamlc nor ocamlopt at this point, just gcc/ar)
> wrap link options passed to ocamlmklib with -ldopt (not -cclib)

- Makefile.rules
- Makefile.tests
- src/ctypes-foreign-base/ffi_call_stubs.c
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-closure-type-promotion/stub-generator/driver.ml
- tests/test-closure-type-promotion/stubs/functions.ml
- tests/test-closure-type-promotion/test_closure_type_promotion.ml
This will fix #441 and related problems on nearly all ARM and MIPS platforms (x86 doesn't seem to be affected because of different calling conventions).
The problems are return results of closures. If integers smaller than word-size are returned, they must be extended to full word-size. But they are currently always zero-extended, never sign-extended (https://github.com/ocamllabs/ocaml-ctypes/blob/0d0c62f5b2432a49c3d0c965b8fa9d0dd50ea857/src/ctypes-foreign-base/ffi_call_stubs.c#L489 ).
The first commit contains test code to demonstrate the issue: `callback_returns_int8_t (fun () -> -128)` will sometimes return `+128`.
If one byte is set to `-128` and the higher bits are set to zero, the whole word will be read as `128`. It's not a problem for the (exclusive) foreign interface, because …
> closure api: always extend integers to full word size

- src/cstubs/cstubs.mli
The code blocks were misformatted. I haven't tested the doc generation with these edits.
> Cstubs.Types.TYPE doc source code formatting

- src/cstubs/cstubs_generate_c.ml
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-lwt-jobs/stubs/functions.ml
- tests/test-lwt-jobs/test_lwt_jobs.ml
- tests/test-lwt-preemptive/stubs/functions.ml
- tests/test-lwt-preemptive/test_lwt_jobs.ml
- tests/test-returning-errno-lwt-jobs/stubs/functions.ml
- tests/test-returning-errno-lwt-jobs/test_returning_errno.ml
- tests/test-returning-errno-lwt-preemptive/stubs/functions.ml
- tests/test-returning-errno-lwt-preemptive/test_returning_errno.ml
This tests that generating lwt job bindings to void-returning functions is broken in `master` and then fixes that defect during stub generation by using `int` for the type of the lwt job `result` field (never initialized or used) and then returning `Val_unit` as the result.
This isn't the prettiest solution but it does unblock me. Please let me know if you'd like to see a different approach used, I'd (probably) be happy to accommodate.
> Lwt return void

- src/ctypes/ctypes_type_printing.ml
- tests/test-type_printing/test_type_printing.ml
Closes #249.
Here are the examples from #249:
```ocaml
let struc = Ctypes.structure ""
let r = field struc "r" float
let g = field struc "g" float
let b = field struc "b" float
let a = field struc "a" float
let () = seal struc
let uni = union ""
let floats = field uni "rgba" (array 4 float)
let struc' = field uni "" struc
let () = seal uni
let struc'' = structure "NVGcolor"
let _ = field struc'' "" uni
let () = seal struc''
```
And here's how those types are printed before and after this change:
```ocaml
- : '_a Static.union typ = union  { float rgba[4]; struct  ;  }
```
```ocaml
- : '_a Ctypes_static.union typ =
union { float rgba[4]; struct { float r; float g; float b; float a;  } ;  }
```
```ocaml
- : '_a Static.structure typ = struct NVGcolor { union  ;  }
```
```ocaml
- : '_a …
```
> Improved printing for tagless structs and unions

- src/cstubs/cstubs_generate_ml.ml
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-foreign_values/stubs/functions.ml
- tests/test-foreign_values/test_foreign_values.ml
Fixes #469.
This PR adds support for binding accessing global array values via generated stubs.  For example, given the C value
```C
char *strings[2] = { "Hello", "world" };
```
the following OCaml expression yields a pointer to `strings` that can be used for reading and writing:
```OCaml
F.foreign "strings" (array 2 string)
```
> Add support for binding foreign arrays

- Makefile
We echo some errors and suggest the user to set "LIBFFI_LIBS" when libffi is not installed.
However, this is suggested value is inconsistent with what the build system really wants. This patch fixes it by suggesting the right value.
> Add -lffi to suggested "LIBFFI_LIBS"

- Makefile.tests
- src/ctypes/unsigned.ml
- src/ctypes/unsigned_stubs.c
- tests/test-marshal/test_marshal.ml
> Register custom operations for unsigned integers

- Makefile.rules
I mean cross-compilation build, specifically.
> Makefile.rules: fix build when shared libraries are not available

- src/cstubs/cstubs.ml
- src/cstubs/cstubs_generate_ml.ml
Avoid generating code that results in warnings for
* incomplete record patterns (9583db9)
* unused variables (a8d2387)
* unused type variables (c911bc4)
Thanks to @MagnusS for the report.
> Avoid a few warnings in generated code

- src/ctypes/ldouble_stubs.c
Simple fix for #502 and a related problem on netbsd. 
I've intentionally not implemented any kind of feature detection. It's tricky. The header definitions are available and the functions are understood by gcc/clang, although they are not implemented by the c  standard library. But gcc will generate opcode for them under certain conditions...
Openbsd seems to have implemented all necessary functions. However their libffi package is currently broken (their newest kernel introduced something similar to grsecurity's mprotect. They've tried to patch libffi accordingly, but it doesn't seem to work as intended)
> work around missing math functions on bsd platforms

- src/cstubs/cstubs.mli
- src/cstubs/cstubs_structs.ml
- src/cstubs/cstubs_structs.mli
It's quite common in C code to create enumerations without tags, so that they can only be referred to by an alias:
```C
typedef enum {
X,
Y,
Z
} xyz;
```
This PR adds support for exposing such types via an optional argument, `typedef`, to the [`enum` function](https://github.com/ocamllabs/ocaml-ctypes/blob/368e1624fe9df189e7f6f90e8b13ecbd74a05b2b/src/cstubs/cstubs.mli#L32).  The `typedef` flag indicates that the name passed to `enum` represents an alias, not an enumeration tag.  With this PR the following code exposes an enueration like `xyz` above,
```ocaml
let i64 n = constant n int64_t
let t = enum "xyz" ~typedef:true [
`X , i64 "X";
`Y , i64 "Y";
`Z , i64 "Z";
]
```
Omitting the `~typedef:true` gives a binding suitable for an enumeration defined with a tag:
```C
enum xyz {
X,
Y,
Z
}; …
```
> Add support for tagless enums.

- src/ctypes-foreign-base/ffi_call_stubs.c
This fixes the support for passing function pointers on platforms that use the no-exec bit in memory.
I believe this may be the underlying cause of issue ctypes #500, as we experienced the same issue when working on improvements for async_ssl.
The code was previously ignoring the function pointer provided by libffi and trying to executing the closure object directly (correct behavior for non no-exec platforms).
> Fix segfault when using funpointer 

- ctypes-foreign.opam
Cf. [opam-repository-mingw metadata](https://github.com/fdopen/opam-repository-mingw/blob/c94d3820/packages/ctypes-foreign/ctypes-foreign.0.4.0/opam#L15).
> Add win32 depexts to ctypes-foreign.

- src/cstubs/cstubs_analysis.ml
- src/cstubs/cstubs_internals.mli
- src/ctypes/ctypes.mli
- src/ctypes/ctypes_bigarray.ml
- src/ctypes/ctypes_bigarray.mli
- src/ctypes/ctypes_bigarray_stubs.ml
- src/ctypes/ctypes_bigarrays.c
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_static.ml
- src/ctypes/ctypes_static.mli
- src/ctypes/ctypes_types.mli
- tests/test-bigarrays/test_bigarrays.ml
This PR adds support for Fortran-layout bigarrays.
[Bigarrays][OCaml_Bigarray] are already closely integrated into ctypes.  For example, it is possible to 
* store bigarrays in larger ctypes values (e.g. as struct fields or array elements)
* pass pointers to bigarrays to C functions
* return pointers to bigarrays from C functions
* allocate bigarray values using ctypes
* create bigarray values from arbitrary pointers
* convert between bigarrays and ctypes arrays
All these features are available via a small number of operations in the interface:
* [`bigarray`][bigarray], [`genarray`][genarray], [`array1`][array1], [`array2`][array2], [`array3`][array3] construct bigarray type descriptions
* [`bigarray_start`][bigarray_start] and [`bigarray_of_ptr`][bigarray_of_ptr] convert between …
> Support for Fortran-layout bigarrays

- Makefile
- Makefile.rules
Without this, each client of ctypes needs to link to `integers` explicitly.
Follow-up to #515.
> Add 'integers' link flags to the ctypes libraries.

- .depend
The `Signed` and `Unsigned` modules are now in a separate package (see #515)
> Update dependencies after unsigned/signed move.

- src/ctypes-foreign-base/ctypes_ffi.ml
- tests/test-views/stub-generator/driver.ml
- tests/test-views/stubs/functions.ml
- tests/test-views/test_views.ml
> Preserve intermediate values from views across foreign calls.

- Makefile.tests
- src/cstubs/cstubs.mli
- src/ctypes/ctypes.ml
- src/ctypes/ctypes.mli
- tests/test-constants/stubs/types.ml
- tests/test-enums/struct-stubs/types.ml
- tests/test-lwt-jobs/stubs/types.ml
- tests/test-lwt-preemptive/stubs/types.ml
- tests/test-returning-errno-lwt-jobs/stubs/types.ml
- tests/test-returning-errno-lwt-preemptive/stubs/types.ml
- tests/test-returning-errno/stubs/types.ml
- tests/test-structs/stubs/types.ml
- tests/test-structs/test_structs.ml
- tests/test-unions/stubs/types.ml
- tests/test-unions/test_unions.ml
This is a follow-up to #537, which has more details.  The high-level aim is described in #528 and #519.
> Move TYPE from cstubs to ctypes

- Makefile.tests
- src/cstubs/cstubs_structs.ml
- src/ctypes/cstubs_internals.ml
- src/ctypes/cstubs_internals.mli
- tests/clib/test_functions.h
- tests/test-type_printing/stub-generator/driver.ml
- tests/test-type_printing/stubs/types.ml
- tests/test-type_printing/test_type_printing.ml
Apparently ctypes sometimes prints references to `typedef`ed enums as `enum foo` instead of `foo`. This patch tries to fix this. I haven't personally tested it, but I believe that it has been tested elsewhere within Jane Street.
> Print typedefed enums correctly

- Makefile
Avoids ["inconsistent assumption" problems](https://github.com/dbuenzli/tsdl/issues/44) with OCaml 4.06.0.
Fixes #552.
> Add -no-keep-locs to the foreign-(un)?threaded build rules.

- src/ctypes/ldouble_stubs.c
- tests/test-ldouble/test_ldouble.ml
The custom operations of ComplexL are broken:
```ocaml
#require "ctypes.top";;
let d1 = LDouble.of_float 1. ;;
let d2 = LDouble.of_float 2. ;;
let c1 = ComplexL.make d1 d2 ;;
let c2 = ComplexL.make d1 d1 ;;
c1 = c2;;
let s1 = Marshal.to_string c1 [] ;;
let s2 = Marshal.to_string c2 [] ;;
s1 = s2;;
let c1':ComplexL.t = Marshal.from_string s1 0 ;;
let c2':ComplexL.t = Marshal.from_string s2 0 ;;
Obj.size (Obj.magic c1) != Obj.size (Obj.magic c1');; (* scary *)
```
It's not captured by the test suite, because marshalling and comparison are both wrong.
And one question: Why is `norm` used inside `ldouble_serialize` https://github.com/ocamllabs/ocaml-ctypes/blob/f2108c7655fe2288ebbca98a12faad54ecc1e22e/src/ctypes/ldouble_stubs.c#L155, but not in `ldouble_deserialize` or …
> fix custom operations of ComplexL

- Makefile
- Makefile.rules
Previously `ocaml_integers.h` was installed once for every sub-package (`ctypes.top`, `ctypes.stubs`, etc.), causing problems for nix and opam2nix (#555).
This PR associates `ocaml_integers.h` with a particular sub-package (`ctypes.stubs`) so that it's installed exactly once.
> Attach ocaml_integers.h to the cstubs sub-package

- .depend
- src/ctypes/ctypes_coerce.mli
coerce.mli seemed unused by the build, it was probably meant for ctypes_coerce.
The other option is that this .mli shouldn't be used at all and deleted altogether I suppose.
> Revive the mli for coercions

- src/ctypes/ctypes.mli
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_types.mli
- tests/test-arrays/test_array.ml
I have already expanded a bit the comments on the FAQ. Feel free to close this PR if you think it's superfluous, but I thought that passing strings in C structure fields and similar type of bindings are probably not that uncommon, and it may be useful to be hinted that `string` views are not the right thing both by the documentation and by the presence of a function like `CArray.of_string`.
> Introduce `CArray.of_string` and expand the `string` view documentation

- src/ctypes/ctypes_memory.ml
This could also be done by using `~initial:'\x00'`, but in this case it may not be worth
as we are replacing almost all the elements anyways.
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> CArray: add the null terminator in of_string

- src/ctypes/ctypes_ptr.ml
Hi,
Since `Signed.S` is defined in `integers` (now separate), additions to this type signature can break `Ctypes_ptr.Raw`.
However, this module is not public API, so it is possible to remove that module type signature, and even to restrict what is exported to the bare minimum: `null` and `nativeint` conversion functions.
Thanks!
> Make Ctypes_ptr.Raw independent from Signed.S

- ctypes.opam
See https://github.com/ocaml/opam-repository/pull/11754
> Constrain lwt to versions below 4.0.0

- .travis.yml
- ctypes.opam
- src/cstubs/cstubs_generate_c.ml
- src/ctypes-foreign-threaded/foreign.ml
- src/ctypes/ctypes_bigarray.ml
- src/ctypes/ctypes_bigarray_stubs.ml
- tests/test-coercions/test_coercions.ml
Restrict OPAM and Travis to require OCaml versions from 4.02 onwards.
Also take advantage of a couple of new features:
* new syntax `let pat : type = expression` (previously `pat` was restricted to variables)
* GADT representations for bigarray element types and layouts
Closes #576
> Drop OCaml 4.01 support

- Makefile.rules
- src/configure/extract_from_c.ml
- src/cstubs/cstubs_structs.ml
- src/ctypes/ctypes_cstubs_internals.h
- tests/test-foreign-errno/test_errno.ml
- tests/test-value_printing/test_value_printing.ml
This will remove `__USE_MINGW_ANSI_STDIO` from the stub generation code. `__USE_MINGW_ANSI_STDIO` must be defined before any other relevant headers are included. This is often not guaranteed because custom headers are added before calls to `Cstubs.write_c`. I've instead added the `ctypes_printf` macro for usage inside generated code, which translates to `__mingw_printf` for mingw, and `printf` otherwise. (Background: On windows one can link again various version of the c stdlib (crt). They are all not really compatible to C99. Instead of adding and testing workarounds for each version, the compatibility layer of mingw is used. This layer is normally enabled by defining `__USE_MINGW_ANSI_STDIO` or by certain compiler switches.)
The second commit removes a dll dependency introduced by OCaml …
> various windows fixes

- src/ctypes/lDouble.ml
- src/ctypes/lDouble.mli
- src/ctypes/ldouble_stubs.c
- tests/test-ldouble/test_ldouble.ml
`long double` must be casted to `intnat` first, not to `uintnat` directly. Otherwise the conversion is undefined behavior for nearly all negative values, see: http://c0x.coding-guidelines.com/6.3.1.4.html , Note 50. 
The code was correct until https://github.com/ocaml/ocaml/commit/24c118d7b63cdab58ed9bad28e2d337e9d1d30ba
. It seems to work as intended on x86 platforms and the CI for ARM still uses OCaml 4.02.3.
> Fix LDouble.to_int

- src/ctypes/ldouble_stubs.c
The result of `Data_custom_Val(caml_alloc_custom(...))` is word
aligned. `long double` and `long double complex` are usually
bigger. Such usage is even wrong on x86/amd64. Compilers are free to
use e.g. the MOVDQA instruction, if you tell them that your pointers are
properly aligned.
> Avoid unaligned stores/loads

- ctypes.opam
See https://github.com/ocamllabs/ocaml-integers/issues/26
> OPAM: constrain integers to < 0.3.0

- Makefile.tests
- ctypes.opam
OCaml 4.01.0 support was dropped in 3243c8974b726cbd67fa1bf044f3cf7137961f12, so it's  now possible to depend on a newer lwt version without ifdefs inside the Makefile.
See https://github.com/ocsigen/lwt/blob/5c2f2d90f898a5bc9889c01b96a2de547c31482f/CHANGES#L96
This should make #601 possible
> update lwt test constrain

- Makefile
- Makefile.rules
- src/discover/commands.mli
- tests/test-variadic/test_variadic.ml
This PR enables `-strict-sequence` and allows building ctypes with it enabled.
This is related to the proposal of enabling -strict-sequence by default in ocaml/ocaml#1971, in order to make ctypes forward compatible.
(I can restrict the PR to the change in `commands.mli` if you would rather avoid modifying the build instructions themselves; although enabling the option there makes sure the issue will not come back later).
> Build with -strict-sequence

- src/ctypes-foreign-base/ctypes_closure_properties.ml
- src/ctypes/ctypes_coerce.ml
Now that ctypes no longer supports OCaml 4.01 (#577), we can use some features from OCaml 4.02.
> Simplify some code using match/exception.

- .travis.yml
Add the Android build to `allow_failures` in the Travis configuration until #581 is fixed.
> Allow the Android build to fail for now.

- ctypes-foreign.opam
This commit syncs the ctypes-foreign.opam with the version downstream in ocaml/opam-repository, and uses the opam 2 style of specifying depexts.  This in turn makes depexts work with a pinned ctypes-foreign, which is useful for automated CI of this repository.
> fix ctypes-foreign depexts to work with opam 2

- src/cstubs/cstubs_generate_ml.ml
- src/ctypes-foreign-base/ctypes_ffi.ml
- src/ctypes-foreign-base/ctypes_ffi_stubs.ml
- src/ctypes/cstubs_internals.ml
- src/ctypes/cstubs_internals.mli
- src/ctypes/ctypes_bigarray.ml
- src/ctypes/ctypes_bigarray.mli
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_ptr.ml
- src/ctypes/ctypes_static.ml
- src/ctypes/ctypes_static.mli
- src/ctypes/ctypes_std_view_stubs.ml
- src/ctypes/ctypes_std_views.ml
- tests/test-raw/test_raw.ml
This internal-only change eliminates the use of `Obj.t` in `Ctypes_ptr.Fat.t`, instead reflecting the type of the `managed` field in the type and using existential types in clients (such as `Ctypes.pointer` and `Ctypes.static_funptr`) to hide the additional type parameter.
This change should eventually make it possible to give a more compact representation to `Foreign.dynamic_funptr` (https://github.com/ocamllabs/ocaml-ctypes/pull/595).
> Reflect "managed" status in the types of fat pointers

- src/ctypes/ctypes_memory_stubs.ml
- src/ctypes/lDouble.ml
Now that we've dropped support for OCaml 4.01 (#577), we can use attributes (`[@@noalloc]`) rather than old-style string annotations (`"noalloc"`).
> Switch 'noalloc' annotations to use attributes.

- src/cstubs/cstubs_generate_c.ml
- src/ctypes/ctypes_cstubs_internals.h
OCaml 4.10 [defaults to the `force-safe-string` mode](https://github.com/ocaml/ocaml/blob/4e6e9123287405a08b349c3e0e12d53000e8534d/Changes#L149-L157), so that the `String_val` macro returns `const char *`.
This PR updates ctypes to generate calls to `Bytes_val` rather than `String_val` for uses of [`ocaml_bytes`](https://github.com/ocamllabs/ocaml-ctypes/blob/ab70b38f1848e8c2ecb726b603f860abf52b146b/src/ctypes/ctypes_types.mli#L212-L213), ensuring `const`-correctness and fixing problems such as the one reported [here](https://github.com/ocamllabs/ocaml-ctypes/issues/134#issuecomment-568168667).
> Distinguish bytes and string in generated stub code

- Makefile
- Makefile.examples
- Makefile.tests
- ctypes.opam
- src/cstubs/cstubs_generate_ml.ml
- src/ctypes/cstubs_internals.mli
- src/ctypes/ctypes.mli
- src/ctypes/ctypes_static.ml
- src/ctypes/ctypes_static.mli
- src/ctypes/ctypes_types.mli
Since OCaml 4.02.0, [`bytes` has been supported as a built-in type in OCaml](https://github.com/ocaml/ocaml/blob/4.02.0/Changes#L15).
Since ctypes no longer supports OCaml 4.01, there's no need to depend on the `base-bytes` library; we can use `bytes` directly instead.
> Remove uses of bytes library

- src/ctypes/ctypes_type_printing.ml
See @fdopen's comment for details: https://github.com/ocamllabs/ocaml-ctypes/pull/622#issuecomment-577394529
> ocaml_bytes corresponds to 'unsigned char *', not 'char *'.

- src/ctypes/cstubs_internals.ml
- src/ctypes/cstubs_internals.mli
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_static.ml
- src/ctypes/ctypes_static.mli
- src/ctypes/ctypes_std_views.ml
The existential type representing the "managed" component in `CPointer` and `Static_funptr` can sometimes escape in generated code (e.g. for inverted stubs: see #628).  Turning it into the concrete type `Obj.t` side-steps the problem.
> Hide the managed component in pointer values

- ctypes-foreign.opam
- ctypes.opam
I tested this by installing Luv, which depends on ctypes, on a system without a `pkg-config` binary. `conf-pkg-config` did not get installed.
I saw that `pkg-config` is also used for something with Xen. I don't know how to best express that as a constraint. However, the Xen-related detection will still work if `pkg-config` happens to be installed, regardless of `conf-pkg-config`.
Fixes #630.
> Move conf-pkg-config dependency to ctypes-foreign

- .github/workflows/test.yml
- ctypes-foreign.opam
This enables GitHub CI, which will in turn activate the CI in #588.  It also adds the depext for Cygwin which enables the Windows port to make progress (and fail in the tests)
> Enable GitHub Actions in master branch

- src/ctypes-foreign-base/dl_stubs.c.unix
- src/ctypes-foreign-base/ffi_call_stubs.c
- src/ctypes/ldouble_stubs.c
- src/ctypes/raw_pointer_stubs.c
- src/ctypes/type_info_stubs.c
- tests/test-type_printing/test_type_printing.ml
In recent versions of OCaml, `String_val` returns `const char*`, not `char *`: https://github.com/ocaml/ocaml/pull/1274
Cf. https://github.com/ocamllabs/ocaml-ctypes/issues/134#issuecomment-605786250 (which is related, but not fixed by this PR).
> Fix some const-related warnings

- src/ctypes-foreign-base/dl.ml.win
See: https://discuss.ocaml.org/t/runtime-error-on-missing-symbols-on-windows/5416
> Report names of missing symbols also under windows

- src/ctypes/complex_stubs.c
- tests/test-complex/test_complex.ml
If too much memory is allocated, the polymorphic comparison function
doesn't work 😜
> fix complex allocation size

- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_memory_stubs.ml
- src/ctypes/type_info_stubs.c
See #597.  This makes the function around twice as fast on my machine.  The changes are:
- Mark `ctypes_write` `[@@noalloc]`
- Improve `CArray.fill` by eliminating some allocations and moving some type dispatch out of the loop
> Speed-up CArray.make with initial value

- src/ctypes/ctypes_cstubs_internals.h
Eliminate the warnings mentioned in https://github.com/ocamllabs/ocaml-ctypes/issues/134#issuecomment-605786250 by casting away `const`.  This temporary fix can be removed when ctypes acquires proper support for cv-qualifiers.
> Interim fix for ocaml_string/const issues

- Makefile
Drop circular dependency in the `ctypes-foreign` target.  See: https://github.com/ocaml/opam-repository/pull/17614#issuecomment-727623389
> Remove circular dependency

- Makefile.tests
If the path of the current build directory contains spaces (or other special chars), the whole build of ocaml-ctypes fails since at one point it uses that path without guards in CFLAGS.
A simple way to reproduce the current bug : 
1. Clone ctypes to "/tmp/space dir"
2. opam install .
Thankfully the fix is simple
> Guard include path with quotes

- README.md
Update the README to use the `ctypes` API documentation with cross references ([example](https://docs.ocaml.pro/html/LIBRARY.ctypes@ctypes.0.17.1/Ctypes/index.html)) from OCamlPro's [documentation hub](https://docs.ocaml.pro) ([announcement](https://discuss.ocaml.org/t/ann-docs-ocaml-pro-an-ocaml-documentation-hub/7718)).
> Link to OCamlPro's API documentation.

- .github/workflows/test.yml
- ctypes.opam
- src/cstubs/cstubs_emit_c.ml
- src/ctypes-foreign/ffi_call_stubs.c
The stubs generation part of ctypes doesn't seem to be compatible with ocaml-multicore at the moment. For instance, the following error message is raised when trying to compile `decompress` which uses ctypes' stubs generation:
```
#=== ERROR while compiling decompress.1.4.1 ===================================#
```
Looking into it, it seems the direct use of `caml_local_roots` stems from a care for backwards compatibility. Given it is relatively easy to simply bump the required version and use the "new" `CAMLdrop()` macro I feel like it might be worth doing anyway.
> Remove compatibility with OCaml 4.02 (makes ctypes stubs compatible with ocaml-multicore for free)

- README.md
> README: fix link to api doc

- .github/workflows/test.yml
> Update CI compiler versions; retire broken Windows+4.12.0 build

- src/ctypes-foreign/ffi_call_stubs.c
This PR makes `make_function_pointer` faster by avoiding a full GC cycle on every invocation.
The documentation of `caml_alloc_custom` (section 9.2 of [the manual](https://ocaml.org/manual/intfc.html#ss:c-custom-alloc)) says:
> Another way to describe the effect of the used and max parameters is in terms of full GC cycles. If you allocate many custom blocks with used / max = 1 / N, the GC will then do one full cycle every N allocations. 
So for used=1, max=1 we make a full GC cycle on every call (or within a small constant factor of that). This is clearly excessive and can be very slow.
I think `caml_alloc_custom_mem` can be used to specify the object size more precisely, but I don't know enough about the code to make that change. Additionally, I'm expecting 0-size to be at most a …
> avoid running a full GC cycle on every FFI closure allocation

- src/discover/discover.ml
Instead of just checking of existence of the `brew` command, make sure that the
existsing `brew ls --versions` command does not end with error.  Still not
really a proper fix for people with a different `brew` command than homebrew,
but it fixes the build in such circumstances at least.
Signed-off-by: Martin Kletzander <nert.pinx@gmail.com>
> More rigorous testing for homebrew

- src/cstubs/cstubs_structs.ml
Example problem:
File "lib/bindings_stubs_field_info.ml", line 17, characters 9-15:
17 |   | View { ty } -> seal ty
^^^^^^
Error (warning 9 [missing-record-field-pattern]): the following labels are not bound in this record pattern:
read, write, format_typ, format
Either bind these labels explicitly or add '; _' to the pattern.
> Fix warning 9 [missing-record-field-pattern] in generated OCaml code

- src/ctypes-foreign/dl.ml.unix
- src/ctypes-foreign/dl.ml.win
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-foreign_values/test_foreign_values.ml
- tests/test-pointers/test_pointers.ml
- tests/test-raw/test_raw.ml
- tests/test-variadic/test_variadic.ml
- tests/test-views/test_views.ml
- Rename local variables to avoid clashes with OCaml's unprefixed exported names
- Replace some calls to deprecated `String` functions
- Disable warnings for unerasable optional arguments and omitted labels
> Eliminate some warnings

- README.md
Add a link to [Building C libraries in OCaml with the dune ctypes stanza](https://michael.bacarella.com/2022/02/19/dune-ctypes/).
> Add link to @mbacarella's dune/ctypes blog post

- tests/test-arrays/test_array.ml
- tests/test-cstdlib/test_cstdlib.ml
- tests/test-pointers/test_pointers.ml
- tests/test-views/test_views.ml
Pervasives is no longer supported in 5.00.0 and is replaced by Stdlib. To be compatible with old version it's not nice to just replace it by Stdlib.
> Pervasives is removed in OCaml 5.00.0+trunk

- Makefile
The logic was wonky here. Now the recipe fails completely if the generation fails. Otherwise the build would continue and later complain about a missing ctypes_primitives.ml obscuring the initial failure.
> Makefile: Fail fast in case of errors

- src/ctypes/ctypes.mli
mention terminating null byte introduced in #563
> update CArray.of_string comment to match reality

- Makefile.rules
The dynlink library has been moved into a subdirectory in the distribution. So in OCaml 5.0 `ctypes.cmxs` is not compiled and not installed.
> Restore compilation of cmxs for 5.0

- tests/test-funptrs/dune
This ensures that `dune runtest -p ctypes` works.
> Attach test_funptrs to ctypes-foreign

- src/cstubs/cstubs_generate_c.ml
This is a draft, untested. Related to https://github.com/yallop/ocaml-ctypes/issues/248#issuecomment-1440045648
> Fix -Wunused-argument for generated C stubs for bytecode

- src/ctypes/ctypes_memory.ml
Change `<-@` to have syntactic arity 2, not 1.
`<-@` used to have syntactic arity 1, given that it is written as nested `fun`s rather than a single `fun` with multiple parameters. In an upcoming version of OCaml 5, this difference will matter a little for performance, as the syntactic arity will start being used as the runtime arity. `<-@` is usually applied to 2 arguments (I claim), so it's a little better for performance for it to have runtime arity 2 and therefore for those applications to be full applications.
This PR is a no-op for OCaml 5.1.1 and earlier.
> Better syntactic arity for fat pointer writes

- src/ctypes/ctypes_bigarray_stubs.ml
Closes #762 by turning the compilation error for the new `Float16` bigarray kind into a run time exception.  We should eventually add proper support for `Float16`: see #763.
> Add catch-all bigarray kind case to avoid OCaml 5.2.0 compilation error

- .github/workflows/test.yml
- avoid duplicate CI runs by restricting push triggering to the master branch
- add configuration for OCaml 5.2
- update the `actions/checkout` action to version 4
> Update CI configuration

- tests/test-callback_lifetime/test_callback_lifetime.ml
As the comment says:
> ```
> (* ...
>   The value of this test is questionable: calling an expired closure does not
>   have defined behaviour, since the structures needed to make the call may
>   have been garbage collected.
> *)
> ```
and there's even less value in the test than there once was, since it's now reliably broken in practice on macOS.
> Remove broken test that calls an expired closure.

- tests/clib/test_functions.c
- tests/clib/test_functions.h
Fix the (passing) `plus_callback` test to test what it's intended to test.
> Fix the plus_callback test.

- src/ctypes/ctypes.mli
- src/ctypes/ctypes_memory.ml
- tests/test-arrays/test_array.ml
Hi !
Working with Ctypes I realized I needed a `CArray.iteri` method in order to iter over a carray passing the index to the argument function. 
As it doesn't exist I felt it was time for me to do my first open source PR :)
`val iteri : (int -> 'a -> unit) -> 'a t -> unit`
This is a new feature, non breaking that just adds a functionality. 
I tried to stick with testing and coding style of the already existing `CArray.iter`function:
- First test checks that the 3 loops of value + index indeed equals 9 ->  `9 = (0 + 1 ) + (1 + 2 ) + (2 + 3) `
- Second test checks with an empty list.
No worry, I just wanted to learn how to do an opensource PR.
> Add CArray.iteri

- examples/fts/stub-generation/bindings/fts_bindings.ml
- examples/fts/stub-generation/bindings/fts_types.ml
- src/cstubs/cstubs_analysis.ml
- src/cstubs/cstubs_generate_c.ml
- src/cstubs/cstubs_generate_ml.ml
- src/ctypes-foreign/ctypes_ffi.ml
- src/ctypes/cstubs_internals.mli
- src/ctypes/ctypes.mli
- src/ctypes/ctypes_memory.ml
- src/ctypes/ctypes_static.ml
- src/ctypes/ctypes_static.mli
- src/ctypes/ctypes_type_printing.ml
- src/ctypes/ctypes_types.mli
- src/ctypes/ctypes_value_printing.ml
- tests/test-cstdlib/stubs/functions.ml
- tests/test-type_printing/test_type_printing.ml
Add two new operations on types:
```ocaml
val const : 'a typ -> 'a typ
(** [const t] const-qualifies the type [t].  At present the only
effect is that the type is marked 'const' in generated code. *)
val volatile : 'a typ -> 'a typ
(** [volatile t] volatile-qualifies the type [t].  At present the only
effect is that the type is marked 'volatile' in generated code. *)
```
> Add support for 'const' and 'volatile'

- src/cstubs/cstubs_generate_ml.ml
- src/ctypes/ctypes_coerce.ml
- src/ctypes/ctypes_std_views.ml
- tests/clib/test_functions.c
- tests/clib/test_functions.h
- tests/test-type_printing/test_type_printing.ml
Also simplify/correct OCaml code generation for cv-qualified types (d90cdb8135958a1e1ec67975ff24a508cd74b60f)
>  Make string a view of ptr (const char), not ptr char

- tests/test-type_printing/test_type_printing.ml
> Allow _Bool to be printed as "_Bool" or "bool" in the tests.

- ctypes-foreign.opam
- ctypes.opam
- dune
- dune-project
- examples/fts/stub-generation/dune
- tests/test-bigarrays/test_bigarrays.ml
As discussed in #588, this uses the proper dune feature instead of OCaml
syntax. It can be merged once requiring dune >= 3.9.0 is acceptable.
> dune: use build_if instead of workaround
