yallop/ocaml-ctypes

.travis-ci.sh
Build OPAM from source to work around ocaml/opam#1853.
Fixes #257.
=> Travis OS X fixes

appveyor.yml, appveyor/build.sh, appveyor/install.sh
* Use AppVeyor to download Wodi. 
* Add an install script for AppVeyor.
=> Fix the AppVeyor build

src/ctypes-foreign-base/ctypes_foreign_basis.ml, src/ctypes-foreign-threaded/foreign.mli, src/ctypes-foreign-unthreaded/foreign.mli
=> Add funptr's optional arguments to funptr_opt.

src/cstubs/cstubs_c_language.ml, src/cstubs/cstubs_emit_c.ml, src/cstubs/cstubs_generate_c.ml, src/cstubs/cstubs_generate_c.mli, src/cstubs/cstubs_inverted.ml, src/cstubs/cstubs_inverted.mli, src/ctypes/ctypes_cstubs_internals.h
=> Add support for releasing runtime lock to Cstubs_inverted

src/configure/make_primitive_details_stubs.c, src/ctypes-foreign-base/ffi_call_stubs.c, src/ctypes/managed_buffer_stubs.c
=> Address some warnings issued by -Wextra

src/ctypes/ctypes_std_view_stubs.ml, src/ctypes/ctypes_std_views.ml, src/ctypes/ctypes_types.mli, src/ctypes/unsigned_stubs.c
=> Support intptr_t and uintptr_t as typedefs

src/ctypes/posixTypes.ml, src/ctypes/posixTypes.mli
=> Support signed arithmetic operations for ssize_t.

src/ctypes/ctypes_memory.ml, src/ctypes/ctypes_std_views.ml
Thanks to @dsheets for the report.
=> Remove a polymorphic comparison to 'null'.

src/cstubs/cstubs.ml, src/cstubs/cstubs_generate_ml.ml
Issue #267 
This is my first change to ctypes so hopefully I caught all the cases.
=> Switch the ordering of the pattern match for Issue 267

src/cstubs/cstubs_generate_ml.ml, src/cstubs/cstubs_inverted.ml, src/cstubs/cstubs_structs.ml
I didn't realize there were more cases.  I *think* these are all of them?
=> Try to fix the rest of the flips

ctypes.opam
=> Add conf-pkg-config as a build dependency.

Makefile, Makefile.rules
=> Build and install *.cmt and *.cmti files.

src/discover/discover.ml
=> Add support for MacPorts

README.md
Better for users and contributors to see at a glance that the repository is in a healthy state.
=> README: move build status to the top

src/ctypes-foreign-base/ffi_type_stubs.c, src/ctypes/ctypes_primitives.h, src/ctypes/type_info_stubs.c
=> Add a prefix to ctypes_primitive enumeration value names.

examples/cstubs_structs/Makefile, examples/cstubs_structs/README.md, examples/cstubs_structs/bindings.ml, examples/cstubs_structs/bindings_c_gen.ml, examples/cstubs_structs/main.ml
I'm not sure if in the repo is the best place for this tutorial, but I think it's kind of nice to have the tutorial tied to the version of code.
Let me know what is wrong or should be expressed better, of course.
=> Add stubs structs tutorial

.travis-ci.sh, .travis.yml, README.md, ctypes.opam
=> Remove support for OCaml 4.00.*

examples/cstubs_structs/Makefile, examples/cstubs_structs/myocamlbuild.ml
I'm not certain these are necessary as the Makefile is pretty good, but for my own purposes I wanted to figure out how to get this step-by-step process working via `ocamlbuild`. Maybe these instructions might be useful for someone else so I wanted to share.
=> Describe how to build structs with OCamlbuild.

src/ctypes/posix_types_stubs.c
Fixes #332.
@mato: are you happy to have this merged?
@avsm: are you still able to test this on OpenBSD?
=> Fixes for NetBSD

src/ctypes-foreign-base/ctypes_ffi.ml, tests/test-callback_lifetime/test_callback_lifetime.ml
=> Take more care to keep values live

src/ctypes/ctypes.mli
=> Expose is_null.

src/ctypes-foreign-base/ffi_call_stubs.c
Just add missing `caml_` prefix to `raise_with_string`
=> raise_with_string --> caml_raise_with_string

tests/clib/test_functions.c, tests/clib/test_functions.h, tests/test-threads/test_threads.ml
Tests were missing in #450 and I just found them again in my local repo
=> add simple test for thread registration

Makefile, Makefile.examples, Makefile.tests
=> make clean: remove all generated files

ctypes.opam
=> Run the date example in the AppVeyor build.

Makefile, ctypes.opam
=> linking fix for integers >= 0.3.0

src/ctypes/ctypes_complex_compatibility.h
=> Reorganize conditional compilation in ctypes_complex_compatibility.h

CHANGES.md, META
Update CHANGES.md and META for 0.16.0
=> Prepare the 0.16.0 release

src/cstubs/cstubs_structs.ml
=> Add a wildcard to code generated to destructure records.

.github/workflows/test.yml
Add a [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) button to the GitHub Actions config.
=> Add a workflow_dispatch button to the GitHub Actions config.

Makefile.tests
=> Link libtest_functions.so with -lm

CHANGES.md
Signed-off-by: Arseniy Alekseyev <aalekseyev@janestreet.com>
=> Fix the reference to PR#651 in changelog

src/ctypes-foreign/dl_stubs.c.unix
(Background: https://github.com/ocaml/ocaml/pull/9534)
=> Remove naked pointers from the Dl library.

README.md
=> Update API link in README to point to ocaml.org.
